import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "PPDB SMA Methodist 1 Palembang",
  description: "Generated by create next app",
};

import ReactQueryProvider from "@/lib/react-query";
import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ReactQueryProvider>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
